# Generated by Django 5.0.4 on 2024-04-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_account_groups_account_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="members",
            field=models.JSONField(default=list),
        ),
    ]
