# Generated by Django 5.0.4 on 2024-04-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_company_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="orders",
            field=models.JSONField(default=list),
        ),
    ]
