# Generated by Django 5.0.4 on 2024-04-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_company_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="orders",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="order",
            name="company",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="member",
            field=models.CharField(max_length=255),
        ),
    ]
