# Generated by Django 5.0.4 on 2024-05-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_account_orders_alter_order_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="area",
            field=models.CharField(default="A", max_length=255),
        ),
    ]
